# STAGE: Create a hash from the git commit UUID, to be used as a tag for docker images
stages:
- stage: Hash
  displayName: Generate Hash
  jobs:
  - job: GenerateTagHashs
    displayName: Generate hash from repository tags
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 60
    steps:
    - template: generate-hash.yml
