parameters:
- name: cpuPool
  displayName: The pool to use for CPU builds
  default: ""
  type: string
- name: developmentRegistry
  displayName: Development Registry URL
  default: ""
  type: string
- name: developmentRegistryServiceConnection
  displayName: Development Registry Service Connection
  default: ""
  type: string
- name: baseImageName
  displayName: Base Image Name
  default: qatk-base
  type: string
- name: libintVersion
  displayName: libint Version to Build
  default: 2.11.1
  type: string
- name: artifactProject
  displayName: Azure DevOps Project ID
  default: ""
  type: string
- name: artifactFeed
  displayName: Azure Artifacts Feed Name
  default: ""
  type: string
- name: libintEnable1Body
  displayName: libint 1-body integral level
  default: 3
  type: number
- name: libintEnableEri
  displayName: libint ERI integral level
  default: 2
  type: number
- name: libintEnableEri3
  displayName: libint ERI3 integral level
  default: 2
  type: number
- name: libintEnableEri2
  displayName: libint ERI2 integral level
  default: 2
  type: number
- name: libintMaxAm
  displayName: libint maximum angular momentum
  default: 4
  type: number
- name: libintOptAm
  displayName: libint optimized angular momentum
  default: 4
  type: number
- name: libintEriMaxAm
  displayName: libint ERI maximum angular momentum
  default: 4
  type: number
- name: libintEriOptAm
  displayName: libint ERI optimized angular momentum
  default: 4
  type: number
- name: libintEnableGenericCode
  displayName: Enable libint generic code
  default: true
  type: boolean
- name: libintEnableContractedInts
  displayName: Enable libint contracted integrals
  default: true
  type: boolean
- name: libintDisableT1G12Support
  displayName: Disable libint T1G12 support
  default: true
  type: boolean
- name: buildJobs
  displayName: Number of parallel build jobs (0 = use all cores)
  default: 0
  type: number

jobs:
- job: BuildLibintPackage
  variables:
    LATEST_TAG: ''
    gitHash: $[stageDependencies.Hash.GenerateTagHashs.outputs['hashingStep.gitHash']]
    march: x86-64-v3
  displayName: Build libint Package
  pool: ${{ parameters.cpuPool }}
  timeoutInMinutes: 1800
  steps:
  - checkout: self
    persistCredentials: true
    path: qatk

  - template: reset-docker-directory.yml

  - task: Docker@2
    displayName: Container repo login
    inputs:
      command: login
      containerRegistry: ${{ parameters.developmentRegistryServiceConnection }}

  # Pull the base image built by the main devcontainer pipeline
  - script: |
      # Check if current branch is main
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      echo "Current branch: $CURRENT_BRANCH"

      if [ "$CURRENT_BRANCH" = "main" ]; then
        # Use gitHash from Hash stage if on main branch
        LATEST_TAG="$(gitHash)"
        echo "On main branch - using gitHash from Hash stage: $LATEST_TAG"
      else
        # Use fixed tag for other branches
        LATEST_TAG="361e28e"
        echo "On branch '$CURRENT_BRANCH' - using fixed tag: $LATEST_TAG"
      fi

      echo "##vso[task.setvariable variable=LATEST_TAG]$LATEST_TAG"
    displayName: Get Latest Base Image Tag

  # Download libint source code from GitHub
  - script: |
      cd $(Agent.BuildDirectory)
      echo "Downloading libint ${{ parameters.libintVersion }} source code from GitHub..."

      # Download the libint source tarball from GitHub releases
      wget https://github.com/evaleev/libint/archive/refs/tags/v${{ parameters.libintVersion }}.tar.gz -O libint-${{ parameters.libintVersion }}.tar.gz

      # Extract the tarball
      tar -xzf libint-${{ parameters.libintVersion }}.tar.gz

      # Rename to standard directory name (GitHub archive extracts to libint-VERSION)
      mv libint-${{ parameters.libintVersion }} libint-source

      echo "libint ${{ parameters.libintVersion }} source downloaded and extracted successfully"
      echo "Source directory contents:"
      ls -la libint-source/ | head -10

      # Keep the original tarball for later packaging
      echo "Downloaded tarball size: $(du -h libint-${{ parameters.libintVersion }}.tar.gz)"
    displayName: Download libint Source Code

  # Prepare directories for build and artifacts
  - script: |
      set -euo pipefail
      mkdir -p $(Agent.BuildDirectory)/libint-build
      mkdir -p $(Agent.BuildDirectory)/artifacts
      echo "Prepared build dir: $(Agent.BuildDirectory)/libint-build"
      echo "Prepared artifacts dir: $(Agent.BuildDirectory)/artifacts"
    displayName: Prepare build and artifacts directories

  # Build libint using the base image
  - script: |
      echo "Building libint ${{ parameters.libintVersion }} using Docker container..."
      echo "Using base image tag: $(LATEST_TAG)"

      docker run --rm \
        -v $(Agent.BuildDirectory)/libint-source:/workspace/libint-source \
        -v $(Agent.BuildDirectory)/libint-build:/workspace/libint-build \
        -v $(Agent.BuildDirectory)/artifacts:/workspace/output \
        -v $(Agent.BuildDirectory)/qatk/.pipelines/install-scripts:/workspace/scripts \
        -e LIBINT_ENABLE_1BODY="${{ parameters.libintEnable1Body }}" \
        -e LIBINT_ENABLE_ERI="${{ parameters.libintEnableEri }}" \
        -e LIBINT_ENABLE_ERI3="${{ parameters.libintEnableEri3 }}" \
        -e LIBINT_ENABLE_ERI2="${{ parameters.libintEnableEri2 }}" \
        -e LIBINT_MAX_AM="${{ parameters.libintMaxAm }}" \
        -e LIBINT_OPT_AM="${{ parameters.libintOptAm }}" \
        -e LIBINT_ERI_MAX_AM="${{ parameters.libintEriMaxAm }}" \
        -e LIBINT_ERI_OPT_AM="${{ parameters.libintEriOptAm }}" \
        -e LIBINT_ENABLE_GENERIC_CODE="${{ parameters.libintEnableGenericCode }}" \
        -e LIBINT_ENABLE_CONTRACTED_INTS="${{ parameters.libintEnableContractedInts }}" \
        -e LIBINT_DISABLE_T1G12_SUPPORT="${{ parameters.libintDisableT1G12Support }}" \
        -e BUILD_JOBS="${{ parameters.buildJobs }}" \
        -w /workspace \
        ${{ parameters.developmentRegistry }}/${{ parameters.baseImageName }}-$(march)-none:$(LATEST_TAG) \
        /bin/bash -c "
          chmod +x /workspace/scripts/build-libint-package.sh &&
          /workspace/scripts/build-libint-package.sh \
            /workspace/libint-source \
            /workspace/libint-build \
            ${{ parameters.libintVersion }} \
            Release \
            $(march) &&
          echo 'Build completed - tarball already in output directory' &&
          echo 'Generated library tarball is available at /workspace/output/libint-${{ parameters.libintVersion }}.tar.gz'
        "
    displayName: Build libint in Docker Container

  # Verify generated artifacts
  - script: |
      cd $(Agent.BuildDirectory)/artifacts
      echo "Verifying generated libint package artifacts..."

      # Check that the generated library tarball exists
      if [ -f "libint-${{ parameters.libintVersion }}.tar.gz" ]; then
        echo "✅ Generated library tarball found: libint-${{ parameters.libintVersion }}.tar.gz"
        echo "Size: $(du -h libint-${{ parameters.libintVersion }}.tar.gz)"
      else
        echo "❌ Error: Generated library tarball not found!"
        exit 1
      fi

      echo "Listing artifacts directory contents:"
      ls -la
      echo "Artifact verification completed."
    displayName: Verify Generated Artifacts

  # Upload libint package to Azure Artifacts
  - task: UniversalPackages@0
    displayName: Upload libint Package to Azure Artifacts
    inputs:
      command: publish
      publishDirectory: $(Agent.BuildDirectory)/artifacts
      feedsToUsePublish: internal
      vstsFeedPublish: ${{ parameters.artifactProject }}/${{ parameters.artifactFeed }}
      vstsFeedPackagePublish: libint-${{ parameters.libintVersion }}.tar.gz
      versionOption: patch
      packagePublishDescription: 'libint ${{ parameters.libintVersion }} compiled package for quantum computing applications'
      publishPackageMetadata: true
      verbosity: Debug
