jobs:
- job: precommit
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.13'
    displayName: Use Python 3.13

  - task: PipAuthenticate@1
    displayName: Pip Authenticate
    inputs:
      artifactFeeds: ''

  - script: pip install pre-commit
    displayName: Install pre-commit

  - script: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    displayName: Run pre-commit
