# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     include:
#     - .pipelines/qdk-azurelinux-base.yaml
#     - .pipelines/bases/azurelinux/*
# # Trigger this pipeline on PRs targeting any branch
# pr:
#   branches:
#     include:
#     - '*'
#   paths:
#     include:
#     - .pipelines/qdk-azurelinux-base.yaml
#     - .pipelines/bases/azurelinux/*
#   drafts: true
# TODO DISABLED TEMPORARILY
trigger: none
pr: none

parameters:
- name: forcePublishing
  displayName: Force the publishing of resulting artifacts
  default: false
  type: boolean
- name: cudaVersion
  displayName: CUDA Version for GPU images
  default: 12.1.0
  type: string
- name: azureLinuxVersion
  displayName: Azure Linux Version
  default: '3.0'
  type: string

resources:
  repositories:
  - repository: self

variables:
- group: QdkChemistry
- name: date
  value: $[format('{0:yyyy}.{0:MM}.{0:dd}', pipeline.startTime)]
- name: baseImageName
  value: azurelinux-base

stages:

# STAGE: Create a hash from the git commit UUID, to be used as a tag for docker images
- template: templates/generate-hash-stage.yml

- stage: BuildQDKAzureLinuxBaseImages
  displayName: Build QDK Azure Linux Base Images
  dependsOn: Hash
  jobs:
  - job: BuildBaseImages
    strategy:
      matrix:
        # CPU-only configurations - AMD64
        cpu_amd64_py310:
          architecture: amd64
          platform: linux/amd64
          pool: $(CPU_POOL_X86)
          pythonVersion: '3.10'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-amd64-py310
        cpu_amd64_py311:
          architecture: amd64
          platform: linux/amd64
          pool: $(CPU_POOL_X86)
          pythonVersion: '3.11'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-amd64-py311
        cpu_amd64_py312:
          architecture: amd64
          platform: linux/amd64
          pool: $(CPU_POOL_X86)
          pythonVersion: '3.12'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-amd64-py312
        cpu_amd64_py313:
          architecture: amd64
          platform: linux/amd64
          pool: $(CPU_POOL_X86)
          pythonVersion: '3.13'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-amd64-py313
        # CPU-only configurations - ARM64
        cpu_arm64_py310:
          architecture: arm64
          platform: linux/arm64
          pool: $(CPU_POOL_ARM)
          pythonVersion: '3.10'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-arm64-py310
        cpu_arm64_py311:
          architecture: arm64
          platform: linux/arm64
          pool: $(CPU_POOL_ARM)
          pythonVersion: '3.11'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-arm64-py311
        cpu_arm64_py312:
          architecture: arm64
          platform: linux/arm64
          pool: $(CPU_POOL_ARM)
          pythonVersion: '3.12'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-arm64-py312
        cpu_arm64_py313:
          architecture: arm64
          platform: linux/arm64
          pool: $(CPU_POOL_ARM)
          pythonVersion: '3.13'
          imageType: cpu
          cudaArch: none
          imageSuffix: cpu-arm64-py313
        # GPU configurations (amd64 only - ARM64 GPU support is limited)
        # H100 GPU (SM90 architecture)
        #sm90_amd64_py310:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.10'
        #  imageType: gpu
        #  cudaArch: '90'
        #  gpuType: h100
        #  imageSuffix: sm90-amd64-py310
        #sm90_amd64_py311:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.11'
        #  imageType: gpu
        #  cudaArch: '90'
        #  gpuType: h100
        #  imageSuffix: sm90-amd64-py311
        #sm90_amd64_py312:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.12'
        #  imageType: gpu
        #  cudaArch: '90'
        #  gpuType: h100
        #  imageSuffix: sm90-amd64-py312
        #sm90_amd64_py313:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.13'
        #  imageType: gpu
        #  cudaArch: '90'
        #  gpuType: h100
        #  imageSuffix: sm90-amd64-py313
      # A100 GPU (SM80 architecture)
        #sm80_amd64_py310:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.10'
        #  imageType: gpu
        #  cudaArch: '80'
        #  gpuType: a100
        #  imageSuffix: sm80-amd64-py310
        #sm80_amd64_py311:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.11'
        #  imageType: gpu
        #  cudaArch: '80'
        #  gpuType: a100
        #  imageSuffix: sm80-amd64-py311
        #sm80_amd64_py312:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.12'
        #  imageType: gpu
        #  cudaArch: '80'
        #  gpuType: a100
        #  imageSuffix: sm80-amd64-py312
        #sm80_amd64_py313:
        #  architecture: amd64
        #  platform: linux/amd64
        #  pool: ${{ parameters.amd64GpuPool }}
        #  pythonVersion: '3.13'
        #  imageType: gpu
        #  cudaArch: '80'
        #  gpuType: a100
        #  imageSuffix: sm80-amd64-py313
      maxParallel: 6
    displayName: Build QDK Azure Linux Base Images
    pool: $(pool)
    timeoutInMinutes: 180
    variables:
      gitHash: $[stageDependencies.Hash.GenerateTagHashs.outputs['hashingStep.gitHash']]
    steps:
    - checkout: self
      persistCredentials: true
      path: qatk

    - template: templates/reset-docker-directory.yml

    - task: Docker@2
      displayName: Container repo login
      inputs:
        command: login
        containerRegistry: $(DEV_ACR_SC)

    # Build Docker image using buildx for multi-platform support
    - script: |
        # Set up Docker buildx for multi-platform builds
        docker buildx create --name qdk-builder --use --bootstrap || true
        docker buildx inspect qdk-builder
      displayName: Setup Docker Buildx

    - task: Docker@2
      displayName: Build QDK Azure Linux Base Image
      inputs:
        command: build
        dockerfile: $(Agent.BuildDirectory)/qatk/.pipelines/bases/azurelinux/Dockerfile
        buildContext: $(Agent.BuildDirectory)/qatk/.pipelines/bases/azurelinux
        repository: $(baseImageName)-$(imageSuffix)
        containerRegistry: $(DEV_ACR_SC)
        arguments: |
          --platform $(platform)
          --build-arg PYTHON_VERSION=$(pythonVersion)
          --build-arg AZURE_LINUX_VERSION=${{ parameters.azureLinuxVersion }}
          --build-arg IMAGE_TYPE=$(imageType)
          --build-arg CUDA_VERSION=${{ parameters.cudaVersion }}
          --build-arg CUDA_ARCH=$(cudaArch)
          --build-arg GPU_TYPE=$(gpuType)
          --build-arg ARCHITECTURE=$(architecture)
        tags: |
          $(gitHash)

    - task: Docker@2
      displayName: Push QDK Azure Linux Base Image
      inputs:
        command: push
        repository: $(baseImageName)-$(imageSuffix)
        containerRegistry: $(DEV_ACR_SC)
        tags: |
          $(gitHash)

    # Test the built image
    - script: |
        echo "Testing the built QDK Azure Linux Base image..."
        docker run --rm --platform $(platform) $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash) /bin/bash -c "
          echo 'Testing Python $(pythonVersion) installation...' &&
          python3 --version &&
          python3 -c 'import sys; print(\"Python version:\", sys.version)' &&
          echo 'Testing basic tools...' &&
          which python3 &&
          which pip3 &&
          pip3 --version &&
          echo 'Testing Azure Linux version...' &&
          cat /etc/os-release | grep -i azure || cat /etc/mariner-release || true &&
          echo 'Testing architecture...' &&
          uname -m &&
          echo 'Testing environment variables...' &&
          env | grep -E '(PYTHON|PATH)' &&
          echo 'QDK Azure Linux Base image test completed successfully!'
        "
      displayName: Test QDK Azure Linux Base Image
      condition: succeeded()

    # Test GPU-specific components for GPU images
    - script: |
        echo "Testing GPU components in the image..."
        docker run --rm --platform $(platform) $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash) /bin/bash -c "
          echo 'Testing CUDA installation...' &&
          nvidia-smi --version || echo 'NVIDIA SMI not available (expected in container)' &&
          nvcc --version || echo 'NVCC not available' &&
          echo 'Testing CUDA libraries...' &&
          ls -la /usr/local/cuda*/lib*/libcudart* || echo 'CUDA runtime libraries not found' &&
          echo 'GPU image test completed!'
        "
      displayName: Test GPU Components
      condition: and(succeeded(), eq(variables['imageType'], 'gpu'))

    # Output image information
    - script: |
        echo "QDK Azure Linux Base Docker image built successfully!"
        echo "Registry: $(DEV_ACR)"
        echo "Image: $(baseImageName)-$(imageSuffix)"
        echo "Hash Tag: $(gitHash)"
        echo "Full image name: $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)"
        echo "Platform: $(platform)"
        echo "Python Version: $(pythonVersion)"
        echo "Image Type: $(imageType)"
        echo "Architecture: $(architecture)"
        if [ "$(imageType)" = "gpu" ]; then
          echo "CUDA Architecture: $(cudaArch)"
          echo "GPU Type: $(gpuType)"
        fi
        echo ""
        echo "To use this image locally:"
        echo "docker pull $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)"
        echo ""
        echo "To run the container:"
        echo "docker run -it --rm $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)"
      displayName: Output Image Information

- stage: PublishLatest
  displayName: Publish Latest Tag
  dependsOn:
  - Hash
  - BuildQDKAzureLinuxBaseImages
  condition: and(succeeded(), or(eq(variables['build.sourceBranch'], 'refs/heads/main'), eq(${{parameters.forcePublishing}}, 'true')))
  jobs:
  - job: PublishLatest
    strategy:
      matrix:
        # CPU-only configurations
        cpu_amd64_py310:
          imageSuffix: cpu-amd64-py310
          platform: linux/amd64
        cpu_amd64_py311:
          imageSuffix: cpu-amd64-py311
          platform: linux/amd64
        cpu_amd64_py312:
          imageSuffix: cpu-amd64-py312
          platform: linux/amd64
        cpu_amd64_py313:
          imageSuffix: cpu-amd64-py313
          platform: linux/amd64
        cpu_arm64_py310:
          imageSuffix: cpu-arm64-py310
          platform: linux/arm64
        cpu_arm64_py311:
          imageSuffix: cpu-arm64-py311
          platform: linux/arm64
        cpu_arm64_py312:
          imageSuffix: cpu-arm64-py312
          platform: linux/arm64
        cpu_arm64_py313:
          imageSuffix: cpu-arm64-py313
          platform: linux/arm64
        # GPU configurations - SM90 (H100)
        #sm90_amd64_py310:
        #  imageSuffix: sm90-amd64-py310
        #  platform: linux/amd64
        #sm90_amd64_py311:
        #  imageSuffix: sm90-amd64-py311
        #  platform: linux/amd64
        #sm90_amd64_py312:
        #  imageSuffix: sm90-amd64-py312
        #  platform: linux/amd64
        #sm90_amd64_py313:
        #  imageSuffix: sm90-amd64-py313
        #  platform: linux/amd64
        # GPU configurations - SM80 (A100)
        #sm80_amd64_py310:
        #  imageSuffix: sm80-amd64-py310
        #  platform: linux/amd64
        #sm80_amd64_py311:
        #  imageSuffix: sm80-amd64-py311
        #  platform: linux/amd64
        #sm80_amd64_py312:
        #  imageSuffix: sm80-amd64-py312
        #  platform: linux/amd64
        #sm80_amd64_py313:
        #  imageSuffix: sm80-amd64-py313
        #  platform: linux/amd64
      maxParallel: 6
    displayName: Publish Latest Tag
    pool: $(CPU_POOL_X86)
    timeoutInMinutes: 60
    variables:
      gitHash: $[stageDependencies.Hash.GenerateTagHashs.outputs['hashingStep.gitHash']]
    steps:
    - template: templates/reset-docker-directory.yml

    - task: Docker@2
      displayName: Container repo login (development)
      inputs:
        command: login
        containerRegistry: $(DEV_ACR_SC)

    - task: Docker@2
      displayName: Container repo login (publishing)
      inputs:
        command: login
        containerRegistry: $(PUB_ACR_SC)

    # Pull the hash-tagged image
    - script: |
        docker pull $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)
      displayName: Pull Hash-Tagged Image

    # Tag and push as latest to development registry
    - script: |
        docker tag $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash) $(DEV_ACR)/$(baseImageName)-$(imageSuffix):latest
        docker push $(DEV_ACR)/$(baseImageName)-$(imageSuffix):latest
      displayName: Push Latest Tag to Development Registry

    # Tag and push to publishing registry if different
    - script: |
        if [ "$(DEV_ACR)" != "$(PUB_ACR)" ]; then
          echo "Publishing to external registry: $(PUB_ACR)"
          docker tag $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash) $(PUB_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)
          docker tag $(DEV_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash) $(PUB_ACR)/$(baseImageName)-$(imageSuffix):latest
          docker push $(PUB_ACR)/$(baseImageName)-$(imageSuffix):$(gitHash)
          docker push $(PUB_ACR)/$(baseImageName)-$(imageSuffix):latest
        else
          echo "Development and publishing registries are the same, skipping duplicate push"
        fi
      displayName: Push to Publishing Registry
      condition: ne('$(PUB_ACR)', '')

    - script: |
        echo "Latest tag published successfully!"
        echo "Development Registry: $(DEV_ACR)/$(baseImageName)-$(imageSuffix):latest"
        if [ "$(DEV_ACR)" != "$(PUB_ACR)" ]; then
          echo "Publishing Registry: $(PUB_ACR)/$(baseImageName)-$(imageSuffix):latest"
        fi
      displayName: Output Publishing Information
