# Pipeline for building and publishing Python wheels for QDK Chemistry
# Only triggered manually

trigger: none
pr: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
  - repository: self
    path: qdk-chemistry

parameters:
- name: matrix
  type: object
  default:
  - name: linux_x86_64
    os: linux
    arch: x86_64
    march: x86-64-v3
    imageName: ubuntu-22.04
  - name: linux_aarch64
    os: linux
    arch: aarch64
    march: armv8-a
    imageName: 1es-pt-azurelinux3-arm
  - name: macos_arm64
    os: macos
    arch: aarch64
    march: armv8-a
    imageName: ACES_VM_SharedPool_Tahoe
- name: publishInternalFeed
  type: boolean
  default: false
- name: publishEsrp
  type: boolean
  default: false

variables:
- group: QdkChemistry
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      autobaseline:
        enableForGitHub: true
      codeql:
        compiled:
          enabled: true
        sourceLanguages: python
        binaryLanguages: cpp
      psscriptanalyzer:
        enabled: false
        justificationForDisabling: Powershell is not used in this repository.
        break: false
      armory:
        enabled: false
        justificationForDisabling: ARM templates are not used in this repository.
        break: false
      eslint:
        enabled: false
        justificationForDisabling: JavaScript is not used in this repository.
        exitOnFatalError: true
      sourceAnalysisPool:
        name: Azure-Pipelines-DevTools-EO
        image: windows-2022
        os: windows
    stages:
    - stage: Build
      displayName: Build C++ Deps and Python Wheels
      jobs:
      - ${{ each target in parameters.matrix }}:
        - job: Build_${{ target.name }}
          ${{ if eq(target.os, 'macos') }}:
            pool:
              name: AcesShared
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
          ${{ elseif eq(target.arch, 'aarch64') }}:
            pool:
              name: $(CPU_POOL_ARM)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}
              hostArchitecture: Arm64
          ${{ else }}:
            pool:
              name: $(CPU_POOL_X86)
              demands:
              - ImageOverride -equals ${{ target.imageName }}
              os: ${{ target.os }}

          timeoutInMinutes: 480
          displayName: Build ${{ target.march }} wheels
          variables:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/lib
          strategy:
            matrix:
              Python3.10:
                pythonVersion: '3.10'
                buildMarch: ${{ target.march }}
              Python3.11:
                pythonVersion: '3.11'
                buildMarch: ${{ target.march }}
              Python3.12:
                pythonVersion: '3.12'
                buildMarch: ${{ target.march }}
              Python3.13:
                pythonVersion: '3.13'
                buildMarch: ${{ target.march }}
            maxParallel: 3
          templateContext:
            outputs:
            - output: pipelineArtifact
              displayName: Upload Python $(pythonVersion) Wheels for ${{ target.os }} ${{ target.march }}
              targetPath: $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse/
              artifactName: ${{ target.os }}-${{ target.arch }}-wheels-python$(pythonVersion)
          steps:
          # Build - Linux x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/build-pip-wheels.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Test - Linux x86_64
          - ${{ if eq(target.arch, 'x86_64') }}:
            - template: .pipelines/templates/test-pip-wheels.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/amd64
                pythonVersion: $(pythonVersion)

          # Build - Linux ARM64
          - ${{ if and(eq(target.arch, 'aarch64'), eq(target.os, 'linux')) }}:
            - template: .pipelines/templates/build-pip-wheels.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

          # Test - Linux ARM64
          - ${{ if and(eq(target.arch, 'aarch64'), eq(target.os, 'linux')) }}:
            - template: .pipelines/templates/test-pip-wheels.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                dockerImage: mcr.microsoft.com/mirror/docker/library/ubuntu:22.04
                imageTag: linux/arm64/v8
                pythonVersion: $(pythonVersion)

          # Build - macOS ARM64
          - ${{ if eq(target.os, 'macos') }}:
            - template: .pipelines/templates/build-pip-wheels.yml@self
              parameters:
                march: $(buildMarch)
                buildTesting: OFF
                enableCoverage: OFF
                agentBuildDirectory: $(Agent.BuildDirectory)
                pythonVersion: $(pythonVersion)
                macBuild: ON

          # Test - macOS ARM64
          - ${{ if eq(target.os, 'macos') }}:
            - template: .pipelines/templates/test-pip-wheels.yml@self
              parameters:
                agentBuildDirectory: $(Agent.BuildDirectory)
                pythonVersion: $(pythonVersion)
                macBuild: ON

          # ARM builds require that we transfer ownership of the wheel directory
          # back to the original base image user
          - ${{ if eq(target.arch, 'aarch64') }}:
            - script: |
                sudo chown -R $(id -u):$(id -g) $(System.DefaultWorkingDirectory)/python/repaired_wheelhouse
              displayName: Fix wheel directory ownership


          - task: TwineAuthenticate@1
            inputs:
              artifactFeed: $(artifactProject)/$(artifactFeed)
            displayName: Authenticate to internal feed
            condition: and(succeeded(), ${{ parameters.publishInternalFeed }})

          - script: |
              cd $(Agent.BuildDirectory)/qdk-chemistry/python
              python3 -m pip install twine
              python3 -m twine upload -r $(artifactFeed) repaired_wheelhouse/*.whl --config-file $(PYPIRC_PATH)
            displayName: Upload wheel with twine
            condition: and(succeeded(), ${{ parameters.publishInternalFeed }})

    - stage: Approval
      displayName: Approval
      dependsOn: Build
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - job: Approval
        pool: server
        timeoutInMinutes: 1440     # job times out in 1 day
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440       # task times out in 1 day
          inputs:
            notifyUsers: ''
            instructions: Please verify artifacts and approve the release
            onTimeout: reject

    - stage: Release
      displayName: Release
      dependsOn: Approval
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'), ${{ parameters.publishEsrp }})
      jobs:
      - job: Publish_Python_Packages
        pool:
          name: Azure-Pipelines-DevTools-EO
          image: ubuntu-latest
          os: linux
        templateContext:
          type: releaseJob
          isProduction: true
          inputs:     # Declare all build artifacts to be consumed in the release job
          - input: pipelineArtifact
            artifactName: linux-x86_64-wheels-python3.10
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-x86_64-wheels-python3.10
          - input: pipelineArtifact
            artifactName: linux-x86_64-wheels-python3.11
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-x86_64-wheels-python3.11
          - input: pipelineArtifact
            artifactName: linux-x86_64-wheels-python3.12
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-x86_64-wheels-python3.12
          - input: pipelineArtifact
            artifactName: linux-x86_64-wheels-python3.13
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-x86_64-wheels-python3.13
          - input: pipelineArtifact
            artifactName: linux-aarch64-wheels-python3.10
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-aarch64-wheels-python3.10
          - input: pipelineArtifact
            artifactName: linux-aarch64-wheels-python3.11
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-aarch64-wheels-python3.11
          - input: pipelineArtifact
            artifactName: linux-aarch64-wheels-python3.12
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-aarch64-wheels-python3.12
          - input: pipelineArtifact
            artifactName: linux-aarch64-wheels-python3.13
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/linux-aarch64-wheels-python3.13
          - input: pipelineArtifact
            artifactName: macos-aarch64-wheels-python3.10
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/macos-aarch64-wheels-python3.10
          - input: pipelineArtifact
            artifactName: macos-aarch64-wheels-python3.11
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/macos-aarch64-wheels-python3.11
          - input: pipelineArtifact
            artifactName: macos-aarch64-wheels-python3.12
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/macos-aarch64-wheels-python3.12
          - input: pipelineArtifact
            artifactName: macos-aarch64-wheels-python3.13
            targetPath: $(System.DefaultWorkingDirectory)/artifacts/macos-aarch64-wheels-python3.13
        steps:
        - script: |
            mkdir -p $(System.DefaultWorkingDirectory)/target/wheels
            find $(System.DefaultWorkingDirectory)/artifacts -name "*.whl" -exec cp {} $(System.DefaultWorkingDirectory)/target/wheels/ \;
            ls $(System.DefaultWorkingDirectory)/target/wheels
          displayName: Collect Python Artifacts for Release

        # Setting the contenttype to the wrong value will allow us to do a dry run of this task without
        # publishing anything, according to the ESRP docs. When debugging, set contenttype: NPM to prevent publishing to PyPI.
        - task: EsrpRelease@9
          condition: succeeded()
          displayName: Publish Python Packages
          inputs:
            connectedservicename: PME ESRP Azure Connection
            usemanagedidentity: true
            keyvaultname: quantum-esrp-kv
            signcertname: ESRPCert
            clientid: 832c049d-cd07-4c1c-bfa5-c07250d190cb
            contenttype: PyPI
            domaintenantid: 975f013f-7f24-47e8-a7d3-abc4752bf346
            folderlocation: $(System.DefaultWorkingDirectory)/target/wheels
            waitforreleasecompletion: true
            owners: davidwillia@microsoft.com, janunsleber@microsoft.com, nathanbaker@microsoft.com
            approvers: davidwillia@microsoft.com, janunsleber@microsoft.com, nathanbaker@microsoft.com
            mainpublisher: ESRPRELPACMAN
